### ISSUE TITLE
just merging images without calculation

### ISSUE THREAD

**Issue by heman1-test** [usnistgov/MIST#39]
Hi,

I have a large(>8000 files) set of images width known grid size and fixed title size. I "just" need to stitch them together without any overlap calculations. Is that possible somehow?

Thank You

**Comment by tblattner** [comment]
Yes that is possible using the  "Preview (0% overlap)". This will assemble it without any overlap calculations and then load it into the ImageJ window. You should be able to then export/save that image from within ImageJ/Fiji.

The button is found here: https://github.com/USNISTGOV/MIST/wiki/User-Guide#input-parameters (see next to "Begin Stitching")

**Comment by mmajurski** [comment]
If you also know the positions, you can use the python utility to just place the images into their grid locations.
https://github.com/usnistgov/MIST/blob/master/assemble_stitched_image.py

**Comment by heman1-test** [comment]
@tblattner 
Preview is no working due to massive final image size / The plugin runs fine with calculation but thats not what I need. I need stitching only. I tried with 0 for horizontal and vertical overlap but than I get black lines between images.
![image](https://github.com/usnistgov/MIST/assets/149710275/9a16b86e-0eb9-4ee3-8061-8e9caf3cf987)



@mmajurski 
What is the limit of that script? The images are RGB images.

**Comment by mmajurski** [comment]
The script should support anything up to system memory.
And the preview is not working in Java because your images have more pixels than can be addressed with 32bit integers. Which is a limitation of the java image package. 
I think anytime we work in that size class, I use the python for assembly, which builds a numpy array of the image, and then uses skimage to save it. And I think the skimage save call uses (or at least can use) bigTiff which has 64bit pixel addresses.

**Comment by heman1-test** [comment]
Thank you @mmajurski  for explaining. But it's a pitty because the plugin can handle that. But with python I'm not so confident with that kind of processing.

**Comment by mmajurski** [comment]
@tblattner do you know of a way to enable bigtiff within the Fiji Plugin?

**Comment by tblattner** [comment]
There is a way to enable SCIFIO in the settings in the screenshot.

Then restart Fiji. Try this out to see if it works. Otherwise, we may need to add an option so that it will write the image to disk!
![fiji_menu](https://github.com/usnistgov/MIST/assets/10550807/e652c02f-2e44-4201-8754-c27a28d3621f)

**Comment by heman1-test** [comment]
Tested it but same result. Preview with 0 overlap still not working. So an option to save it to disk would be a highly appreciated feature :-)

**Comment by tblattner** [comment]
An update has been pushed. Update MIST from the "Help->Update..." 

The new update now falls back to saving a temp.ome.tiff image into your specified output directory in the output options.

**Comment by heman1-test** [comment]
Hi @tblattner thank you. 
It looks as expected. Maybe you can implement a checkbox where to choose if preview should be save or not.
